### ISSUE TITLE
Windows 10, unable to install

### ISSUE THREAD

**Issue by roccomuso** [chjj/tty.js#158]
`
gyp ERR! build error
gyp ERR! stack Error:`C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "c:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd c:\Users\Rocco\Desktop\pc-notify\node_modules\tty.js\node_modules\pty.js
gyp ERR! node -v v0.12.6
gyp ERR! node-gyp -v v2.0.1
## gyp ERR! not ok

> ws@0.4.32 install c:\Users\Rocco\Desktop\pc-notify\node_modules\tty.js\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

\
c:\Users\Rocco\Desktop\pc-notify\node_modules\tty.js\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws>if not defined npm_config_node_gyp (node "c:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Compilazione dei progetti nella soluzione uno alla volta. Per abilitare la compilazione parallela, aggiungere l'opzione "/m".
  bufferutil.cc
     Creating library c:\Users\Rocco\Desktop\pc-notify\node_modules\tty.js\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\build\Release\bufferutil.lib and object c:\User
  s\Rocco\Desktop\pc-notify\node_modules\tty.js\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\build\Release\bufferutil.exp
  Generating code
  Finished generating code
  bufferutil.vcxproj -> c:\Users\Rocco\Desktop\pc-notify\node_modules\tty.js\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\build\Release\bufferutil.node
  validation.cc
     Creating library c:\Users\Rocco\Desktop\pc-notify\node_modules\tty.js\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\build\Release\validation.lib and object c:\User
  s\Rocco\Desktop\pc-notify\node_modules\tty.js\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\build\Release\validation.exp
  Generating code
  Finished generating code
  validation.vcxproj -> c:\Users\Rocco\Desktop\pc-notify\node_modules\tty.js\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws\build\Release\validation.node
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "c:\Program Files\nodejs\node.exe" "c:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "i" "--save" "tty.js"
npm ERR! node v0.12.6
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pty.js@0.3.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Users\Rocco\Desktop\pc-notify\npm-debug.log
`

**Comment by TaylorHuston** [comment]
Same issue for me I believe 
[npm-debug.zip](https://github.com/chjj/tty.js/files/201660/npm-debug.zip)

**Comment by vasudevsykam** [comment]
Install and set path for python may solve the issue.
